In [1]:
%load_ext autoreload
%autoreload 2
import torch
from utils import get_mnist_data
from models import ConvNN
from training_and_evaluation import evaluate_robustness_smoothing

# Project 2, part 4: Randomized smoothing certification (20 pt)
In this notebook we compare the robustness of the classifiers from Parts 1-3 via randomized smoothing.

## Your task
Complete the missing code in the respective files, i.e. `models.py`, `training_and_evaluation.py`, `attacks.py`, and this notebook. Make sure that all the functions follow the provided specification, i.e. the output of the function exactly matches the description in the docstring. 

Specifically, for this part you will have to implement the following functions / classes:  
**`training_and_evaluation.py`**:
* `evaluate_robustness_smoothing` (20pt)

## General remarks

Do not add or modify any code outside of the following comment blocks, or where otherwise explicitly stated.
``` python
##########################################################
# YOUR CODE HERE
...
##########################################################
```
After you fill in all the missing code, restart the kernel and re-run all the cells in the notebook.

The following things are **NOT** allowed:
- Using additional `import` statements
- Copying / reusing code from other sources (e.g. code by other students)

If you plagiarise even for a single project task, you won't be eligible for the bonus this semester.

In [2]:
mnist_testset = get_mnist_data(train=False)
use_cuda = torch.cuda.is_available()
model = ConvNN()
if use_cuda:
    model = model.cuda()
    
num_samples_1 = int(1e2)  # reduce this to 1e2 in case it takes too long, e.g. because you don't have CUDA
num_samples_2 = int(1e3)  # reduce this to 1e3 in case it takes too long, e.g. because you don't have CUDA
certification_batch_size = int(5e2)  # reduce this to 5e2 if required (e.g. not enough memory)
sigma = 1
alpha = 0.05

In [3]:
training_types = ['standard_training', "adversarial_training", "randomized_smoothing"]

### Robustness certification
Here we first load the checkpoints for the base classifiers of the different training methods of Parts 1-3. Then, perform robustness certification of the smooth classifier via randomized smoothing. For this, you need to implement `evaluate_robustness_smoothing` from `training_and_evaluation.py`. Follow the docstring in that file.

In [4]:
results = {}

for training_type in training_types:
    model.load_state_dict(torch.load(f"models/{training_type}.checkpoint"))
    certification_results = evaluate_robustness_smoothing(model, sigma, mnist_testset, num_samples_1=num_samples_1,
                                                          num_samples_2=num_samples_2, alpha=alpha, 
                                                          certification_batch_size=certification_batch_size)
    results[training_type] = certification_results


tensor([2, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 3, 8, 8, 8, 3, 3, 8, 0, 8, 2, 8, 8, 3,
        8, 8, 2, 8, 3, 8, 3, 3, 8, 3, 2, 8, 2, 8, 7, 2, 8, 8, 8, 8, 8, 8, 8, 8,
        8, 8, 8, 8, 8, 3, 8, 8, 2, 8, 8, 8, 2, 0, 8, 2, 8, 8, 8, 8, 8, 2, 8, 8,
        2, 8, 3, 3, 3, 8, 8, 2, 3, 8, 8, 8, 8, 2, 8, 8, 2, 2, 8, 8, 8, 3, 8, 3,
        2, 8, 8, 8])
tensor([8, 8, 2, 3, 8, 3, 8, 3, 3, 8, 2, 3, 8, 3, 8, 8, 8, 8, 8, 8, 3, 3, 8, 8,
        8, 8, 2, 8, 8, 8, 0, 8, 2, 3, 8, 8, 3, 8, 3, 2, 3, 3, 8, 8, 8, 2, 2, 8,
        8, 8, 8, 8, 8, 2, 2, 8, 8, 8, 8, 8, 8, 8, 8, 3, 2, 8, 2, 8, 8, 8, 8, 2,
        2, 8, 8, 8, 3, 8, 7, 2, 3, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 3, 3, 8, 2, 8,
        3, 8, 8, 2, 8, 8, 8, 8, 8, 2, 3, 8, 8, 2, 8, 8, 8, 8, 3, 8, 8, 8, 8, 8,
        8, 8, 8, 8, 8, 8, 7, 8, 2, 3, 8, 8, 8, 8, 8, 3, 8, 8, 8, 3, 3, 8, 8, 8,
        2, 8, 3, 8, 3, 8, 8, 8, 8, 8, 8, 8, 8, 0, 3, 8, 8, 3, 8, 8, 3, 8, 8, 8,
        8, 8, 8, 8, 2, 8, 8, 3, 2, 3, 7, 3, 8, 8, 8, 8, 2, 8, 8, 8, 2, 8, 3, 3,
        8, 8, 8, 8,

tensor([8, 8, 8, 8, 8, 8, 8, 8, 2, 8, 2, 8, 8, 2, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
        8, 8, 2, 8, 8, 2, 2, 8, 2, 2, 2, 8, 8, 8, 8, 2, 8, 8, 2, 8, 8, 8, 8, 8,
        8, 8, 8, 8, 8, 2, 8, 8, 8, 8, 8, 2, 2, 8, 2, 8, 2, 8, 2, 2, 8, 8, 8, 8,
        8, 8, 8, 8, 8, 8, 8, 8, 8, 3, 8, 8, 8, 8, 2, 2, 8, 8, 2, 8, 8, 8, 2, 2,
        2, 2, 8, 4, 8, 2, 8, 8, 2, 2, 8, 2, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
        2, 2, 8, 8, 2, 8, 8, 8, 8, 8, 8, 8, 2, 8, 8, 2, 8, 8, 8, 8, 8, 8, 8, 8,
        8, 8, 8, 8, 2, 8, 8, 2, 8, 8, 8, 8, 8, 8, 3, 8, 2, 8, 8, 8, 8, 8, 8, 8,
        8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
        8, 2, 8, 2, 8, 8, 8, 8, 8, 0, 8, 8, 8, 8, 8, 8, 8, 8, 8, 2, 8, 8, 8, 8,
        8, 8, 3, 8, 8, 8, 8, 2, 8, 2, 8, 2, 8, 8, 3, 8, 8, 8, 8, 8, 0, 8, 8, 8,
        8, 8, 8, 8, 2, 8, 8, 0, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 3, 8,
        8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 2, 8,
        8, 8, 8, 8, 8, 8, 2, 8, 8, 8, 8,

tensor([8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 3, 8, 8, 8,
        8, 8, 8, 8, 8, 3, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
        8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
        8, 8, 8, 8, 8, 8, 8, 8, 3, 8, 8, 8, 2, 3, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
        8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 3, 8, 8, 8, 8, 8, 8,
        8, 8, 8, 8, 8, 8, 8, 8, 8, 3, 8, 8, 2, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
        8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 2, 8, 8, 8, 8, 8, 3, 8, 8, 8, 8, 8,
        8, 8, 8, 8, 8, 8, 3, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
        8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 3, 8, 8, 8, 8, 8, 8, 8,
        8, 8, 8, 8, 3, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 3, 8, 8,
        8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
        8, 3, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
        8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,

tensor([8, 0, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 0, 0, 2, 8, 8, 8, 8, 8, 8, 8, 8,
        8, 0, 8, 8, 8, 8, 8, 8, 0, 8, 8, 8, 0, 8, 8, 8, 0, 8, 8, 8, 8, 8, 0, 8,
        8, 8, 8, 8, 0, 8, 8, 8, 0, 8, 8, 0, 8, 8, 8, 8, 8, 8, 8, 0, 0, 8, 0, 8,
        8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 0, 8, 8, 8, 2, 8, 8, 8, 8, 8, 0,
        8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 0, 8, 8, 8, 2, 8, 8, 8, 8, 8, 0,
        8, 8, 0, 8, 8, 0, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 0, 8, 8,
        8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 0, 8, 8, 8, 8, 8, 8, 8, 0, 0, 8, 8, 8, 8,
        8, 8, 8, 2, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 0, 8, 8, 8, 8, 8,
        8, 8, 8, 8, 8, 8, 0, 8, 8, 8, 0, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
        8, 8, 8, 8, 8, 0, 8, 8, 8, 8, 8, 8, 0, 8, 8, 0, 8, 8, 8, 0, 8, 8, 8, 8,
        8, 8, 8, 8, 8, 8, 8, 0, 8, 0, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
        2, 8, 8, 0, 8, 8, 8, 8, 8, 8, 8, 8, 8, 0, 2, 0, 8, 8, 8, 8, 8, 0, 8, 8,
        0, 8, 8, 8, 8, 0, 8, 8, 8, 8, 8,

8
tensor([1])
tensor([8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
        8, 8, 0, 8, 8, 8, 8, 8, 3, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
        8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
        3, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
        8, 8, 8, 8])
tensor([8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
        8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 3, 8, 8, 8, 8, 8, 8, 8, 8, 3, 8, 8, 8,
        8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 3, 8, 8, 8, 8, 8, 8, 8, 8,
        8, 3, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
        8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
        8, 8, 8, 8, 8, 3, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
        8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 3, 8, 8, 8, 8, 8, 8, 8, 8,
        8, 8, 8, 8, 8, 8, 3, 8, 8, 8, 8, 8, 8, 3, 8, 8, 8, 2, 8, 8, 8, 8, 8, 8,
     

tensor([8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 3, 8,
        8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 2, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
        3, 8, 8, 8, 8, 8, 3, 8, 8, 8, 2, 8, 8, 8, 2, 8, 8, 8, 8, 8, 8, 8, 8, 8,
        2, 8, 8, 8, 8, 2, 8, 8, 4, 8, 3, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
        8, 2, 8, 8])
tensor([8, 8, 0, 8, 8, 8, 8, 3, 8, 8, 8, 8, 8, 8, 8, 2, 8, 8, 8, 8, 2, 8, 3, 8,
        8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 2, 8, 8, 8, 8, 8, 8, 8, 8, 8,
        8, 8, 2, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
        8, 8, 8, 8, 8, 8, 2, 8, 8, 8, 8, 8, 8, 2, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
        8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 2, 8, 8, 8, 8, 8, 8, 8, 9,
        2, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
        8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 3, 8, 2, 8, 3, 8, 8, 8, 8, 8, 8,
        8, 8, 3, 2, 8, 8, 8, 8, 8, 2, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
        8, 8, 8, 8,

KeyboardInterrupt: 

### Robustness comparison
Compare the robustness of the different training types. As we can see, robust training via randomized smoothing leads to the best robustness.

Note that the number of certified points will be lower in case you had to reduce the number of samples for performance reasons.

In [6]:
for k,v in results.items():
    print(f"{k}: correct_certified {v['correct_certified']}, avg. certifiable radius: {v['avg_radius']}")

standard_training: correct_certified 2087, avg. certifiable radius: 0.13772809505462646
adversarial_training: correct_certified 2408, avg. certifiable radius: 0.17466765642166138
randomized_smoothing: correct_certified 7707, avg. certifiable radius: 0.7908596396446228
